### ISSUE TITLE
please enable Vi keybindings in the terminal settings.

### ISSUE THREAD

**Issue by Amarlanda** [warpdotdev/keysets#5]
There is a large number of users who use (VIm style ((and even Emac users)) key bindings on the command line))

Something like [this](https://github.com/jeffreytse/zsh-vi-mode) vi mode for zsh, would be awesome! No vi mode is such a deal breaker for me.  :(

**Comment by elviskahoro** [comment]
@Amarlanda We're tracking this issue here:
https://github.com/warpdotdev/Warp/issues/159

The tldr; the Input Editor is a custom built UI element. And so support for Vi mode would necessitate building out all the functionality natively. It isn't something that can just be toggled / enabled. We're not relying on the shell for the input, hence why Warp supports modern Mac keybindings.

**Comment by danielmiessler** [comment]
So we're saying this just isn't going to happen then?

So I can stop looking at Warp then as an option? 

I cannot live life with Vim commands to navigate my command history, edit commands, etc.

**Comment by elviskahoro** [comment]
So we're saying this just isn't going to happen then?

It won't happen within the next couple of quarters, because of the engineering lift. I closed this issue because we're tracking it in https://github.com/warpdotdev/Warp/issues/159

> So I can stop looking at Warp then as an option?
I'd advice subscribing to notifications for issue 159 so that when it does launch you get an email.
